{'ARTICLE_EXCLUDES': ['pages'],
 'ARTICLE_LANG_SAVE_AS': '{slug}-{lang}.html',
 'ARTICLE_LANG_URL': '{slug}-{lang}.html',
 'ARTICLE_ORDER_BY': 'reversed-date',
 'ARTICLE_PATHS': [''],
 'ARTICLE_PERMALINK_STRUCTURE': '',
 'ARTICLE_SAVE_AS': '{slug}.html',
 'ARTICLE_TRANSLATION_ID': 'slug',
 'ARTICLE_URL': '{slug}.html',
 'AUTHOR': 'Morteza',
 'AUTHOR_FEED_ATOM': None,
 'AUTHOR_FEED_RSS': None,
 'AUTHOR_SAVE_AS': 'author/{slug}.html',
 'AUTHOR_URL': 'author/{slug}.html',
 'BIND': '',
 'CACHE_CONTENT': False,
 'CACHE_PATH': 'cache',
 'CATEGORY_FEED_ATOM': None,
 'CATEGORY_SAVE_AS': 'category/{slug}.html',
 'CATEGORY_URL': 'category/{slug}.html',
 'CHECK_MODIFIED_METHOD': 'mtime',
 'CONTENT_CACHING_LAYER': 'reader',
 'COPYRIGHT_NAME': 'Morteza ZAKERI. All rights reserved.',
 'COPYRIGHT_YEAR': '2017 - 2019',
 'CSS_FILE': 'main.css',
 'CUSTOM_CSS': '/static/css/custom.css',
 'DATE_FORMATS': {},
 'DAY_ARCHIVE_SAVE_AS': '',
 'DAY_ARCHIVE_URL': '',
 'DEBUG': False,
 'DEFAULT_CATEGORY': 'misc',
 'DEFAULT_DATE_FORMAT': '%a %d %B %Y',
 'DEFAULT_LANG': 'en',
 'DEFAULT_METADATA': {},
 'DEFAULT_ORPHANS': 0,
 'DEFAULT_PAGINATION': 5,
 'DELETE_OUTPUT_DIRECTORY': False,
 'DIRECT_TEMPLATES': ['index', 'tags', 'categories', 'authors', 'archives'],
 'DISPLAY_CATEGORIES_ON_MENU': True,
 'DISPLAY_PAGES_ON_MENU': True,
 'DOCUTILS_SETTINGS': {},
 'DRAFT_LANG_SAVE_AS': 'drafts/{slug}-{lang}.html',
 'DRAFT_LANG_URL': 'drafts/{slug}-{lang}.html',
 'DRAFT_PAGE_LANG_SAVE_AS': 'drafts/pages/{slug}-{lang}.html',
 'DRAFT_PAGE_LANG_URL': 'drafts/pages/{slug}-{lang}.html',
 'DRAFT_PAGE_SAVE_AS': 'drafts/pages/{slug}.html',
 'DRAFT_PAGE_URL': 'drafts/pages/{slug}.html',
 'DRAFT_SAVE_AS': 'drafts/{slug}.html',
 'DRAFT_URL': 'drafts/{slug}.html',
 'EXTRA_PATH_METADATA': {},
 'FAVICON': '/static/img/favicon.ico',
 'FEED_ALL_ATOM': None,
 'FEED_DOMAIN': '',
 'FEED_MAX_ITEMS': '',
 'FILENAME_METADATA': '(?P<date>\\d{4}-\\d{2}-\\d{2}).*',
 'FORMATTED_FIELDS': ['summary'],
 'GITHUB_URL': 'https://github.com/m-zakeri/',
 'GZIP_CACHE': True,
 'HOME_HIDE_TAGS': False,
 'I18N_TEMPLATES_LANG': 'en',
 'IGNORE_FILES': ['.#*'],
 'INDEX_SAVE_AS': 'index.html',
 'INTRASITE_LINK_REGEX': '[{|](?P<what>.*?)[|}]',
 'JINJA_ENVIRONMENT': {'extensions': [],
                       'lstrip_blocks': True,
                       'trim_blocks': True},
 'JINJA_FILTERS': {},
 'LINKS': (('Our Laboratory',
            'http://parsa.iust.ac.ir/reverse-engineering-lab/'),
           ('Our Micropedia', 'http://micropedia.ir'),
           ('My University Page',
            'http://webpages.iust.ac.ir/morteza_zakeri/')),
 'LOAD_CONTENT_CACHE': False,
 'LOCALE': [''],
 'LOG_FILTER': [],
 'MAIN_MENU': True,
 'MARKDOWN': {'extension_configs': {'markdown.extensions.codehilite': {'css_class': 'highlight'},
                                    'markdown.extensions.extra': {},
                                    'markdown.extensions.meta': {}},
              'output_format': 'html5'},
 'MENUITEMS': (('Archives', '/archives.html'),
               ('Categories', '/categories.html'),
               ('Tags', '/tags.html'),
               ('Sitemap', '/sitemap.xml')),
 'MONTH_ARCHIVE_SAVE_AS': '',
 'MONTH_ARCHIVE_URL': '',
 'NEWEST_FIRST_ARCHIVES': True,
 'OUTPUT_PATH': 'output',
 'OUTPUT_RETENTION': [],
 'OUTPUT_SOURCES': False,
 'OUTPUT_SOURCES_EXTENSION': '.text',
 'PAGE_EXCLUDES': [''],
 'PAGE_LANG_SAVE_AS': 'pages/{slug}-{lang}.html',
 'PAGE_LANG_URL': 'pages/{slug}-{lang}.html',
 'PAGE_ORDER_BY': 'basename',
 'PAGE_PATHS': ['pages'],
 'PAGE_SAVE_AS': 'pages/{slug}.html',
 'PAGE_TRANSLATION_ID': 'slug',
 'PAGE_URL': 'pages/{slug}.html',
 'PAGINATED_TEMPLATES': {'author': None,
                         'category': None,
                         'index': None,
                         'tag': None},
 'PAGINATION_PATTERNS': [PaginationRule(min_page=1, URL='{name}{extension}', SAVE_AS='{name}{extension}'),
                         PaginationRule(min_page=2, URL='{name}{number}{extension}', SAVE_AS='{name}{number}{extension}')],
 'PATH': 'D:\\AnacondaProjects\\m-zakeri.github.io\\content',
 'PATH_METADATA': '',
 'PELICAN_CLASS': 'pelican.Pelican',
 'PLUGINS': ['sitemap'],
 'PLUGIN_PATHS': ['D:\\AnacondaProjects\\pelican-addon-clones\\pelican-plugins'],
 'PORT': 8000,
 'PYGMENTS_RST_OPTIONS': {},
 'READERS': {},
 'RELATIVE_URLS': False,
 'REVERSE_CATEGORY_ORDER': False,
 'RSS_FEED_SUMMARY_ONLY': True,
 'SITELOGO': '/static/img/profile.png',
 'SITEMAP': {'changefreqs': {'articles': 'monthly',
                             'indexes': 'daily',
                             'pages': 'monthly'},
             'format': 'xml',
             'priorities': {'articles': 0.6, 'indexes': 0.6, 'pages': 0.5}},
 'SITENAME': 'Morteza ZAKERI',
 'SITESUBTITLE': 'Ph.D. Student, Computer Engineering',
 'SITETITLE': 'Morteza ZAKERI',
 'SITEURL': '',
 'SLUGIFY_SOURCE': 'title',
 'SLUG_REGEX_SUBSTITUTIONS': [('[^\\w\\s-]', ''),
                              ('(?u)\\A\\s*', ''),
                              ('(?u)\\s*\\Z', ''),
                              ('[-\\s]+', '-')],
 'SOCIAL': (('linkedin', 'https://www.linkedin.com/in/mortazazakeri/'),
            ('twitter', 'https://twitter.com/_zakeri_'),
            ('github', 'https://github.com/m-zakeri/'),
            ('github', 'https://github.com/mortazazakeri/'),
            ('rss', '/feeds/all.atom.xml')),
 'STATIC_CHECK_IF_MODIFIED': False,
 'STATIC_CREATE_LINKS': False,
 'STATIC_EXCLUDES': [],
 'STATIC_EXCLUDE_SOURCES': True,
 'STATIC_PATHS': ['static/img/', 'static/pdf/', 'static/css/'],
 'STATIC_SAVE_AS': '{path}',
 'STATIC_URL': '{path}',
 'SUMMARY_MAX_LENGTH': 50,
 'TAG_SAVE_AS': 'tag/{slug}.html',
 'TAG_URL': 'tag/{slug}.html',
 'TEMPLATE_EXTENSIONS': ['.html'],
 'TEMPLATE_PAGES': {},
 'THEME': 'D:\\AnacondaProjects\\m-zakeri.github.io\\Flex',
 'THEME_STATIC_DIR': 'theme',
 'THEME_STATIC_PATHS': ['static'],
 'THEME_TEMPLATES_OVERRIDES': [],
 'TIMEZONE': 'Asia/Tehran',
 'TRANSLATION_FEED_ATOM': None,
 'TWITTER_USERNAME': '_zakeri_',
 'TYPOGRIFY': True,
 'TYPOGRIFY_IGNORE_TAGS': [],
 'USE_FOLDER_AS_CATEGORY': True,
 'WITH_FUTURE_DATES': True,
 'WRITE_SELECTED': [],
 'YEAR_ARCHIVE_SAVE_AS': '',
 'YEAR_ARCHIVE_URL': ''}
